<a href="https://colab.research.google.com/github/QaziSaim/DeepLearning--DeepNeuralNetwork-/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook

In [1]:
print("Hello I'm excited to learn PyTorch!")

Hello I'm excited to learn PyTorch!


In [5]:
# !nvidia-smi

In [3]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [4]:
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
vector = torch.tensor([7, 7 ])

In [9]:
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
# Matrixm
matrix = torch.tensor([[7,9], [1,3]])
matrix

tensor([[7, 9],
        [1, 3]])

In [13]:
matrix.ndim

2

In [14]:
matrix.shape

torch.Size([2, 2])

In [15]:
matrix[0]

tensor([7, 9])

In [16]:
matrix[1]

tensor([1, 3])

In [30]:
# Tensor
tensor = torch.tensor([[[1,2,3,4,5],
                        [3,6,9,4,5],
                        [2,5,4,5,4],
                        [1,2,3,6,1]]])

In [31]:
tensor

tensor([[[1, 2, 3, 4, 5],
         [3, 6, 9, 4, 5],
         [2, 5, 4, 5, 4],
         [1, 2, 3, 6, 1]]])

In [32]:
tensor.ndim

3

In [33]:
tensor.shape

torch.Size([1, 4, 5])

In [21]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

In [ ]:
# Random Tensors
