<a href="https://colab.research.google.com/github/QaziSaim/DeepLearning--DeepNeuralNetwork-/blob/main/Basic_Tensorflow_Understanding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [23]:
matrix_a = tf.constant([[1,2],[3,4]])
matrix_a = tf.cast(tf.constant([[1,2],[3,4],[3,4]]),tf.float32)

matrix_b = tf.constant([[6,7],[8,9]])

In [28]:
tf.shape(matrix_b)[-1]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [27]:
dk = tf.cast(tf.shape(matrix_b)[-1],tf.float32)
dk

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [29]:
tf.math.sqrt(dk)

<tf.Tensor: shape=(), dtype=float32, numpy=1.4142135381698608>

In [9]:
import numpy as np
t_b = np.array(matrix_b)
matrix_a @ t_b.T

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 26],
       [46, 60]], dtype=int32)>

In [13]:
matrix_a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [12]:
t_b.T

array([[6, 8],
       [7, 9]], dtype=int32)

In [10]:
matrix_a @ matrix_b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 25],
       [50, 57]], dtype=int32)>

In [31]:
result = tf.matmul(matrix_a,matrix_b,transpose_b=True)
result = tf.cast(result,tf.float32)

InvalidArgumentError: cannot compute MatMul as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:MatMul] name: 

In [49]:
resutl = tf.cast(result,dtype=tf.float32)

In [51]:
scaled_logits = resutl/tf.math.sqrt(dk)

In [52]:
weights = tf.nn.softmax(scaled_logits,axis=-1)

In [54]:
tf.nn.softmax(scaled_logits)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.4166025e-02, 9.8583394e-01],
       [5.0197548e-05, 9.9994981e-01]], dtype=float32)>

In [53]:
weights

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.4166025e-02, 9.8583394e-01],
       [5.0197548e-05, 9.9994981e-01]], dtype=float32)>

In [4]:
matrix_a * matrix_b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6, 14],
       [24, 36]], dtype=int32)>

In [5]:
matrix_a @ matrix_b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 25],
       [50, 57]], dtype=int32)>

In [34]:
dk

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [46]:
tf.nn.softmax([tf.math.sqrt(dk),tf.math.sqrt(dk),tf.math.sqrt(dk)],axis=-1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.33333334, 0.33333334, 0.33333334], dtype=float32)>

In [47]:
tf.nn.softmax([tf.math.sqrt(dk),tf.math.sqrt(dk),tf.math.sqrt(dk)])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.33333334, 0.33333334, 0.33333334], dtype=float32)>

TypeError: 'module' object is not callable