<a href="https://colab.research.google.com/github/QaziSaim/DeepLearning--DeepNeuralNetwork-/blob/main/JournyBasicPyTorchTutorialsOne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [3]:
print(x_data.shape)
print(type(x_data))
print(x_data)

torch.Size([2, 2])
<class 'torch.Tensor'>
tensor([[1, 2],
        [3, 4]])


In [4]:
np_array = np.array(data)
print(type(np_array))
print(np_array)
torch_to_np = torch.from_numpy(np_array)
print(type(torch_to_np))
print(torch_to_np)

<class 'numpy.ndarray'>
[[1 2]
 [3 4]]
<class 'torch.Tensor'>
tensor([[1, 2],
        [3, 4]])


In [5]:
x_ones = torch.ones_like(x_data)
print(x_ones)

tensor([[1, 1],
        [1, 1]])


In [9]:
x_rand  = torch.rand_like(torch.Tensor([0,1]),dtype = torch.float)

In [10]:
x_rand

tensor([0.5012, 0.3038])

In [12]:
np_array.shape

(2, 2)

In [21]:
torch.rand_like(torch.Tensor(np_array))

tensor([[0.2825, 0.2208],
        [0.9083, 0.3274]])

In [22]:
torch.ones(np_array.shape[0])

tensor([1., 1.])

In [23]:
torch.zeros(np_array.shape[1])

tensor([0., 0.])

In [24]:
torch.rand(3,4)

tensor([[0.9302, 0.2692, 0.9367, 0.7778],
        [0.1808, 0.1613, 0.8986, 0.6754],
        [0.0773, 0.5468, 0.9406, 0.6479]])

In [25]:
torch.is_tensor(torch.Tensor(np_array))

True

In [26]:
torch.is_tensor(np_array)

False

In [29]:
torch.is_storage(x_data)

False

In [30]:
storage_obj = torch.FloatStorage(6)
print(storage_obj)

 7.323356628417969
 0.0
 9.798751831054688
 0.0
 1.1210387714598537e-43
 0.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]


/tmp/ipython-input-3872303776.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage_obj = torch.FloatStorage(6)


In [31]:
torch.is_storage(storage_obj)

True

In [32]:
tensor_obj = torch.randn(4, 6)
print(f"Tensor object: {tensor_obj}")

# Check if it's a storage
is_storage_tensor = torch.is_storage(tensor_obj)
print(f"Is it a storage? {is_storage_tensor}")


Tensor object: tensor([[-1.0670,  2.3809,  0.0636,  0.4092,  0.4002, -0.3642],
        [-0.9611,  3.1050, -0.2776, -0.6782,  0.7331, -0.3433],
        [ 0.3438,  0.7749, -1.4219,  0.7867,  0.5342,  1.3412],
        [-0.1271,  1.0125,  0.2849,  1.1636, -0.5587,  0.4323]])
Is it a storage? False


In [36]:
complex_data = torch.Tensor([1,2,3])
print(torch.is_complex(complex_data))

False


In [37]:
complex_data = torch.tensor([1+2j,2+4j],dtype=torch.complex64)

In [38]:
torch.is_complex(complex_data)

True