<a href="https://colab.research.google.com/github/QaziSaim/DeepLearning--DeepNeuralNetwork-/blob/main/JournyBasicPyTorchTutorialsOne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##### https://docs.pytorch.org/docs/stable/torch.html
##### https://docs.pytorch.org/docs/stable/generated/torch.rand_like.html
##### https://docs.pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html


In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [3]:
print(x_data.shape)
print(type(x_data))
print(x_data)

torch.Size([2, 2])
<class 'torch.Tensor'>
tensor([[1, 2],
        [3, 4]])


In [4]:
np_array = np.array(data)
print(type(np_array))
print(np_array)
torch_to_np = torch.from_numpy(np_array)
print(type(torch_to_np))
print(torch_to_np)

<class 'numpy.ndarray'>
[[1 2]
 [3 4]]
<class 'torch.Tensor'>
tensor([[1, 2],
        [3, 4]])


In [5]:
x_ones = torch.ones_like(x_data)
print(x_ones)

tensor([[1, 1],
        [1, 1]])


In [9]:
x_rand  = torch.rand_like(torch.Tensor([0,1]),dtype = torch.float)

In [10]:
x_rand

tensor([0.5012, 0.3038])

In [12]:
np_array.shape

(2, 2)

In [21]:
torch.rand_like(torch.Tensor(np_array))

tensor([[0.2825, 0.2208],
        [0.9083, 0.3274]])

In [22]:
torch.ones(np_array.shape[0])

tensor([1., 1.])

In [23]:
torch.zeros(np_array.shape[1])

tensor([0., 0.])

In [24]:
torch.rand(3,4)

tensor([[0.9302, 0.2692, 0.9367, 0.7778],
        [0.1808, 0.1613, 0.8986, 0.6754],
        [0.0773, 0.5468, 0.9406, 0.6479]])

In [25]:
torch.is_tensor(torch.Tensor(np_array))

True

In [26]:
torch.is_tensor(np_array)

False

In [29]:
torch.is_storage(x_data)

False

In [30]:
storage_obj = torch.FloatStorage(6)
print(storage_obj)

 7.323356628417969
 0.0
 9.798751831054688
 0.0
 1.1210387714598537e-43
 0.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]


/tmp/ipython-input-3872303776.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage_obj = torch.FloatStorage(6)


In [31]:
torch.is_storage(storage_obj)

True

In [32]:
tensor_obj = torch.randn(4, 6)
print(f"Tensor object: {tensor_obj}")

# Check if it's a storage
is_storage_tensor = torch.is_storage(tensor_obj)
print(f"Is it a storage? {is_storage_tensor}")


Tensor object: tensor([[-1.0670,  2.3809,  0.0636,  0.4092,  0.4002, -0.3642],
        [-0.9611,  3.1050, -0.2776, -0.6782,  0.7331, -0.3433],
        [ 0.3438,  0.7749, -1.4219,  0.7867,  0.5342,  1.3412],
        [-0.1271,  1.0125,  0.2849,  1.1636, -0.5587,  0.4323]])
Is it a storage? False


In [36]:
complex_data = torch.Tensor([1,2,3])
print(torch.is_complex(complex_data))

False


In [37]:
complex_data = torch.tensor([1+2j,2+4j],dtype=torch.complex64)

In [38]:
torch.is_complex(complex_data)

True

In [39]:
torch.is_conj(complex_data)

False

In [40]:
y = torch.conj(complex_data)

In [41]:
type(y)

torch.Tensor

In [42]:
torch.is_conj(y)

True

In [53]:
float_data = torch.Tensor([1.0,2.0,3.0])
# float_data = torch.Tensor(torch.randn(3),dtype=torch.float)
type(float_data.dtype)

torch.dtype

In [50]:
[torch.randn(3)]

[tensor([ 0.7256, -0.7843,  0.5738])]

In [55]:
torch.is_floating_point(float_data)

True

In [63]:
try:
  assert torch.is_nonzero(torch.Tensor([0.]))
except Exception as e:
  print(e)

In [61]:
assert torch.is_nonzero(torch.Tensor([1.]))

In [64]:
torch.tensor([1.2,3]).dtype

torch.float32

In [68]:
torch.tensor([1.2,3j]).dtype

torch.complex128

In [78]:
torch.set_default_dtype(torch.float64)
# if i used float 16 it give complex32 initilize , if bflao16 is use it will raise error
# if i used float 32 it give 64 for 64 it give 128

In [79]:
torch.tensor([1j,1.2]).dtype

torch.complex128

In [81]:
torch.get_default_dtype()

torch.float64

In [84]:
torch.get_default_device()

device(type='cpu')

In [88]:
torch.set_default_device('cpu')

In [89]:
torch.get_default_device()

device(type='cpu')

In [2]:
import torch


In [3]:
torch.cuda.set_device('cuda:1')

RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


In [4]:
torch.tensor([1.2, 3]).dtype

torch.float32

In [7]:
torch.set_default_tensor_type(torch.DoubleTensor)
# this is deprecated



In [8]:
torch.tensor([1.2, 3]).dtype

torch.float64

In [9]:
a = torch.randn(1,2,3,4,5,6)
torch.numel(a)

720

In [12]:
a = torch.zeros(4,4)
torch.numel(a)

16

In [13]:
torch.set_printoptions(precision=2)


In [14]:
torch.tensor([1.12345])

tensor([1.12])

In [17]:
torch.set_printoptions(threshold=10)

In [18]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
torch.set_printoptions(profile='default')


In [20]:
torch.tensor([1.12345])


tensor([1.1235])

In [21]:
torch.arange(10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
torch.set_flush_denormal(True)

True

In [23]:
torch.tensor([1e-323], dtype=torch.float64)


tensor([0.])

In [24]:
torch.set_flush_denormal(False)


True

In [25]:
torch.tensor([1e-323], dtype=torch.float64)


tensor([9.8813e-324])