<a href="https://colab.research.google.com/github/QaziSaim/DeepLearning--DeepNeuralNetwork-/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
print(torch.__version__)

2.9.0+cu126


In [3]:
 ### Introduction to tensor

In [4]:
# scalar
scalar =  torch.tensor(7)

In [5]:
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
vector = torch.tensor([3,7])

In [9]:
vector

tensor([3, 7])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
scalar.shape

torch.Size([])

In [16]:
vector.size()

torch.Size([2])

In [22]:
MATRIX =  torch.tensor([[7,3,8],[9,1,3]])
MATRIX

tensor([[7, 3, 8],
        [9, 1, 3]])

In [23]:
MATRIX.shape

torch.Size([2, 3])

In [24]:
MATRIX.size()

torch.Size([2, 3])

In [25]:
TENSOR = torch.tensor([[1,2,3],[3,6,9],[2,4,5]])

In [26]:
TENSOR

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [27]:
TENSOR.shape

torch.Size([3, 3])

In [29]:
TENSOR.size()

torch.Size([3, 3])

In [30]:
TENSOR.ndim

2

In [32]:
random_tensor = torch.rand(size=(3,4))
print(random_tensor)

tensor([[0.8359, 0.3707, 0.4205, 0.1841],
        [0.8271, 0.0946, 0.7048, 0.9373],
        [0.4849, 0.2298, 0.5472, 0.9530]])


In [34]:
random_image = torch.rand(size=(224,224,3))
random_image.shape, random_image.size(), random_image.ndim

(torch.Size([224, 224, 3]), torch.Size([224, 224, 3]), 3)

In [36]:
zeros = torch.zeros(size=(3,4))
zeros,zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [37]:
ones = torch.ones(size=(3,4))
ones,ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [39]:
zero_to_ten_deprecated = torch.range(0, 10)
zero_to_ten_deprecated

/tmp/ipython-input-201814837.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [41]:
zero_to_ten = torch.arange(0,10,2)
zero_to_ten

tensor([0, 2, 4, 6, 8])

In [43]:
five_zero = torch.zeros_like(zero_to_ten)
five_zero

tensor([0, 0, 0, 0, 0])

In [44]:
five_ones = torch.ones_like(zero_to_ten)
five_ones

tensor([1, 1, 1, 1, 1])

#### Precision is the amount of detail used to describe a number.

