<a href="https://colab.research.google.com/github/QaziSaim/DeepLearning--DeepNeuralNetwork-/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
print(torch.__version__)

2.9.0+cu126


In [ ]:
 ### Introduction to tensor

In [ ]:
# scalar
scalar =  torch.tensor(7)

In [ ]:
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([3,7])

In [ ]:
vector

tensor([3, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
scalar.shape

torch.Size([])

In [ ]:
vector.size()

torch.Size([2])

In [ ]:
MATRIX =  torch.tensor([[7,3,8],[9,1,3]])
MATRIX

tensor([[7, 3, 8],
        [9, 1, 3]])

In [ ]:
MATRIX.shape

torch.Size([2, 3])

In [ ]:
MATRIX.size()

torch.Size([2, 3])

In [ ]:
TENSOR = torch.tensor([[1,2,3],[3,6,9],[2,4,5]])

In [ ]:
TENSOR

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR.shape

torch.Size([3, 3])

In [ ]:
TENSOR.size()

torch.Size([3, 3])

In [ ]:
TENSOR.ndim

2

In [ ]:
random_tensor = torch.rand(size=(3,4))
print(random_tensor)

tensor([[0.8359, 0.3707, 0.4205, 0.1841],
        [0.8271, 0.0946, 0.7048, 0.9373],
        [0.4849, 0.2298, 0.5472, 0.9530]])


In [ ]:
random_image = torch.rand(size=(224,224,3))
random_image.shape, random_image.size(), random_image.ndim

(torch.Size([224, 224, 3]), torch.Size([224, 224, 3]), 3)

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros,zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
ones = torch.ones(size=(3,4))
ones,ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [ ]:
zero_to_ten_deprecated = torch.range(0, 10)
zero_to_ten_deprecated

/tmp/ipython-input-201814837.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
zero_to_ten = torch.arange(0,10,2)
zero_to_ten

tensor([0, 2, 4, 6, 8])

In [ ]:
five_zero = torch.zeros_like(zero_to_ten)
five_zero

tensor([0, 0, 0, 0, 0])

In [ ]:
five_ones = torch.ones_like(zero_to_ten)
five_ones

tensor([1, 1, 1, 1, 1])

#### Precision is the amount of detail used to describe a number.



In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device


(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],dtype=torch.half) #)torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
some_tensor = torch.rand(3,4)

print(some_tensor)
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Device tensor is stored on: {some_tensor.device}')

tensor([[0.5799, 0.8165, 0.0055, 0.2349],
        [0.1719, 0.7304, 0.3723, 0.9226],
        [0.4964, 0.8297, 0.5121, 0.0998]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor -= 10
tensor

tensor([-9, -8, -7])

In [ ]:
tensor

tensor([-9, -8, -7])

In [ ]:
tensor += 10

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
torch.multiply(tensor,10)

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [ ]:
torch.mul(tensor,tensor)

tensor([1, 4, 9])

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 467 µs, sys: 0 ns, total: 467 µs
Wall time: 485 µs


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)


CPU times: user 520 µs, sys: 0 ns, total: 520 µs
Wall time: 397 µs


tensor(14)

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]],dtype=torch.float32)

In [ ]:
tensor_A.shape

torch.Size([3, 2])

In [ ]:
tensorBA = torch.tensor([[7, 10],
                         [3,4],
                         [5,6]],dtype=torch.float32)

In [ ]:
torch.matmul(tensor_A,tensorBA.reshape(2,3))

tensor([[15., 20., 15.],
        [37., 50., 33.],
        [59., 80., 51.]])

In [ ]:
torch.matmul(tensor_A,tensorBA.T)

tensor([[27., 11., 17.],
        [61., 25., 39.],
        [95., 39., 61.]])

In [ ]:
tensorBA.T

tensor([[ 7.,  3.,  5.],
        [10.,  4.,  6.]])

In [ ]:
tensorBA.reshape(2,3)

tensor([[ 7., 10.,  3.],
        [ 4.,  5.,  6.]])

In [ ]:
tensorBA

tensor([[ 7., 10.],
        [ 3.,  4.],
        [ 5.,  6.]])

In [ ]:
torch.mm(tensor_A,tensorBA.T)

tensor([[27., 11., 17.],
        [61., 25., 39.],
        [95., 39., 61.]])

In [ ]:
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")


Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [4]:
import torch

In [5]:
x = torch.arange(0, 100, 10)

In [6]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [7]:
x.min(), x.max(), x.type(torch.float32).mean(), x.sum()

(tensor(0), tensor(90), tensor(45.), tensor(450))

In [8]:
tensor = torch.arange(10, 100, 10)
print(tensor)
tensor.argmax(), tensor.argmin()

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])


(tensor(8), tensor(0))

In [9]:
tensor = torch.arange(10., 100., 10.)
tensor

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [10]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [13]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)