<a href="https://colab.research.google.com/github/QaziSaim/DeepLearning--DeepNeuralNetwork-/blob/main/Pytorch_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor = torch.rand(7,7)

In [ ]:
tensor

tensor([[0.6138, 0.9472, 0.6489, 0.8061, 0.9629, 0.8800, 0.8399],
        [0.7501, 0.1050, 0.2560, 0.9233, 0.9364, 0.3466, 0.2527],
        [0.7812, 0.5305, 0.3748, 0.8632, 0.4462, 0.8747, 0.5490],
        [0.8818, 0.7240, 0.4743, 0.3454, 0.7689, 0.4514, 0.3529],
        [0.3219, 0.3630, 0.9297, 0.5675, 0.0726, 0.2459, 0.1491],
        [0.9045, 0.6241, 0.7384, 0.1855, 0.5600, 0.2713, 0.7039],
        [0.5196, 0.2700, 0.7294, 0.2368, 0.3057, 0.7842, 0.8166]])

In [ ]:
matrix_a = torch.rand(1,7)
matrix_b = torch.rand(1,7)
print(f'Matrix Mulitplication of matrix A and Matrix B\n {matrix_a * matrix_b}')
print(f'Dot Mulitplication:\n {matrix_a.mul(matrix_b)}')


Matrix Mulitplication of matrix A and Matrix B
 tensor([[0.7552, 0.4306, 0.1644, 0.3861, 0.4651, 0.2712, 0.1051]])
Dot Mulitplication:
 tensor([[0.7552, 0.4306, 0.1644, 0.3861, 0.4651, 0.2712, 0.1051]])


In [ ]:
matrix_a @ matrix_b.T

tensor([[2.5777]])

In [ ]:
torch.manual_seed(0)
tensor = torch.rand(7,7)
print('The tensor:\n ',tensor)
matrix_a = torch.rand(1,7)
matrix_b = torch.rand(1,7)
print(f'Matrix Mulitplication of matrix A and Matrix B\n {matrix_a * matrix_b}')
print(f'Dot Mulitplication:\n {matrix_a.mul(matrix_b)}')


The tensor:
  tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
Matrix Mulitplication of matrix A and Matrix B
 tensor([[0.2859, 0.0921, 0.1530, 0.1688, 0.4122, 0.5856, 0.0419]])
Dot Mulitplication:
 tensor([[0.2859, 0.0921, 0.1530, 0.1688, 0.4122, 0.5856, 0.0419]])


In [ ]:
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape


(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [3]:
x = torch.rand([3,7])

In [4]:
x

tensor([[0.9745, 0.4432, 0.8356, 0.9430, 0.1718, 0.6116, 0.0242],
        [0.5883, 0.0671, 0.5016, 0.8272, 0.0156, 0.8708, 0.2538],
        [0.7427, 0.5014, 0.4036, 0.2620, 0.3810, 0.1996, 0.3756]])

In [5]:
x_bool = x.ge(0.5)

In [6]:
x_bool

tensor([[ True, False,  True,  True, False,  True, False],
        [ True, False,  True,  True, False,  True, False],
        [ True,  True, False, False, False, False, False]])

In [8]:
x_masked = torch.masked_select(x,x_bool)

In [9]:
x_masked

tensor([0.9745, 0.8356, 0.9430, 0.6116, 0.5883, 0.5016, 0.8272, 0.8708, 0.7427,
        0.5014])

In [12]:
y = torch.empty(5,7,3)

In [13]:
y

tensor([[[1.5766e-19, 5.6419e-11, 2.3062e-12],
         [5.6419e-11, 2.3068e-12, 5.6419e-11],
         [1.3992e-08, 1.4580e-19, 3.3747e+27],
         [3.0282e-18, 1.3153e+34, 1.7860e+31],
         [1.6458e+19, 1.1432e+27, 2.1707e-18],
         [2.7345e+20, 1.6928e+22, 1.1287e+27],
         [2.3075e-12, 5.6419e-11, 2.9423e+26]],

        [[1.7699e+31, 7.7447e+31, 2.3085e-12],
         [5.6419e-11, 2.9423e+26, 1.7699e+31],
         [7.7447e+31, 3.0283e-18, 1.3153e+34],
         [1.7860e+31, 1.6458e+19, 6.9772e+22],
         [2.3086e-12, 5.6419e-11, 4.7270e+27],
         [2.3082e-12, 5.6419e-11, 4.8405e+30],
         [6.5957e+22, 2.3084e-12, 5.6419e-11]],

        [[4.8405e+30, 2.7664e+29, 4.5451e+30],
         [2.1707e-18, 2.7345e+20, 1.4580e-19],
         [3.3747e+27, 4.5160e+27, 2.3082e-12],
         [5.6419e-11, 1.7439e+28, 2.1707e-18],
         [4.4632e-20, 4.4553e-41, 2.1707e-18],
         [1.7921e+25, 1.4580e-19, 3.3747e+27],
         [4.5152e+27, 2.3082e-12, 5.6419e-11]],

       