<a href="https://colab.research.google.com/github/QaziSaim/DeepLearning--DeepNeuralNetwork-/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
print(torch.__version__)

2.9.0+cu126


In [ ]:
 ### Introduction to tensor

In [ ]:
# scalar
scalar =  torch.tensor(7)

In [ ]:
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([3,7])

In [ ]:
vector

tensor([3, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
scalar.shape

torch.Size([])

In [ ]:
vector.size()

torch.Size([2])

In [ ]:
MATRIX =  torch.tensor([[7,3,8],[9,1,3]])
MATRIX

tensor([[7, 3, 8],
        [9, 1, 3]])

In [ ]:
MATRIX.shape

torch.Size([2, 3])

In [ ]:
MATRIX.size()

torch.Size([2, 3])

In [ ]:
TENSOR = torch.tensor([[1,2,3],[3,6,9],[2,4,5]])

In [ ]:
TENSOR

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR.shape

torch.Size([3, 3])

In [ ]:
TENSOR.size()

torch.Size([3, 3])

In [ ]:
TENSOR.ndim

2

In [ ]:
random_tensor = torch.rand(size=(3,4))
print(random_tensor)

tensor([[0.8359, 0.3707, 0.4205, 0.1841],
        [0.8271, 0.0946, 0.7048, 0.9373],
        [0.4849, 0.2298, 0.5472, 0.9530]])


In [ ]:
random_image = torch.rand(size=(224,224,3))
random_image.shape, random_image.size(), random_image.ndim

(torch.Size([224, 224, 3]), torch.Size([224, 224, 3]), 3)

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros,zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
ones = torch.ones(size=(3,4))
ones,ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [ ]:
zero_to_ten_deprecated = torch.range(0, 10)
zero_to_ten_deprecated

/tmp/ipython-input-201814837.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
zero_to_ten = torch.arange(0,10,2)
zero_to_ten

tensor([0, 2, 4, 6, 8])

In [ ]:
five_zero = torch.zeros_like(zero_to_ten)
five_zero

tensor([0, 0, 0, 0, 0])

In [ ]:
five_ones = torch.ones_like(zero_to_ten)
five_ones

tensor([1, 1, 1, 1, 1])

#### Precision is the amount of detail used to describe a number.



In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device


(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],dtype=torch.half) #)torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
some_tensor = torch.rand(3,4)

print(some_tensor)
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Device tensor is stored on: {some_tensor.device}')

tensor([[0.5799, 0.8165, 0.0055, 0.2349],
        [0.1719, 0.7304, 0.3723, 0.9226],
        [0.4964, 0.8297, 0.5121, 0.0998]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor -= 10
tensor

tensor([-9, -8, -7])

In [ ]:
tensor

tensor([-9, -8, -7])

In [ ]:
tensor += 10

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
torch.multiply(tensor,10)

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [ ]:
torch.mul(tensor,tensor)

tensor([1, 4, 9])

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 467 µs, sys: 0 ns, total: 467 µs
Wall time: 485 µs


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)


CPU times: user 520 µs, sys: 0 ns, total: 520 µs
Wall time: 397 µs


tensor(14)

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]],dtype=torch.float32)

In [ ]:
tensor_A.shape

torch.Size([3, 2])

In [ ]:
tensorBA = torch.tensor([[7, 10],
                         [3,4],
                         [5,6]],dtype=torch.float32)

In [ ]:
torch.matmul(tensor_A,tensorBA.reshape(2,3))

tensor([[15., 20., 15.],
        [37., 50., 33.],
        [59., 80., 51.]])

In [ ]:
torch.matmul(tensor_A,tensorBA.T)

tensor([[27., 11., 17.],
        [61., 25., 39.],
        [95., 39., 61.]])

In [ ]:
tensorBA.T

tensor([[ 7.,  3.,  5.],
        [10.,  4.,  6.]])

In [ ]:
tensorBA.reshape(2,3)

tensor([[ 7., 10.,  3.],
        [ 4.,  5.,  6.]])

In [ ]:
tensorBA

tensor([[ 7., 10.],
        [ 3.,  4.],
        [ 5.,  6.]])

In [ ]:
torch.mm(tensor_A,tensorBA.T)

tensor([[27., 11., 17.],
        [61., 25., 39.],
        [95., 39., 61.]])

In [ ]:
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")


Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [4]:
import torch

In [5]:
x = torch.arange(0, 100, 10)

In [6]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [7]:
x.min(), x.max(), x.type(torch.float32).mean(), x.sum()

(tensor(0), tensor(90), tensor(45.), tensor(450))

In [8]:
tensor = torch.arange(10, 100, 10)
print(tensor)
tensor.argmax(), tensor.argmin()

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])


(tensor(8), tensor(0))

In [9]:
tensor = torch.arange(10., 100., 10.)
tensor

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [10]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [13]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [1]:
import torch

In [2]:
x = torch.arange(1. , 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [3]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [4]:
y_reshaped = x.reshape(7,1)
y_reshaped, y_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.]]),
 torch.Size([7, 1]))

In [5]:
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [6]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [7]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [8]:
print(f'Previous tensor: {x_reshaped}')
print(f'Previos tensor shape: {x_reshaped.shape}')

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previos tensor shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [9]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x.shape)  # torch.Size([2, 3])


torch.Size([2, 3])


In [10]:
y = torch.unsqueeze(x, 0)
print(y.shape)

torch.Size([1, 2, 3])


In [11]:
z = torch.unsqueeze(x, 1)
print(z.shape)  # torch.Size([4, 1])


torch.Size([2, 1, 3])


In [31]:
torch.unsqueeze(x,2)

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])

In [27]:
x.ndim

2

In [34]:
x_original = torch.rand(size=(224,224,3))
x_original.shape, x_original.ndim, x_original.size()

(torch.Size([224, 224, 3]), 3, torch.Size([224, 224, 3]))

In [37]:
x_original.permute(1, 2, 0).shape

torch.Size([224, 3, 224])

In [38]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [41]:
x[0], x[0][0], x[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [42]:
x[:, 0]

tensor([[1, 2, 3]])

In [44]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [45]:
x[:,1,1]

tensor([5])

In [46]:
x[0,0,:]

tensor([1, 2, 3])

In [62]:
x[0,:,2]

tensor([3, 6, 9])

In [69]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor, array.dtype, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 dtype('float64'),
 torch.float64)

In [70]:
array += 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [71]:
import torch
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f'Tensor A:\n{random_tensor_A}\n')
print(f'Tensor B:\n{random_tensor_B}\n')
print(f'Does Tensor A is equal Tensor B? (anywhere)')
random_tensor_A==random_tensor_B

Tensor A:
tensor([[0.6697, 0.9755, 0.7514, 0.7072],
        [0.8009, 0.6947, 0.1250, 0.4635],
        [0.3525, 0.3141, 0.9370, 0.5241]])

Tensor B:
tensor([[0.4061, 0.4749, 0.8927, 0.0224],
        [0.2859, 0.7992, 0.1812, 0.3609],
        [0.4271, 0.4810, 0.2841, 0.6582]])

Does Tensor A is equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [72]:
import torch
import random

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)


torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f'Tensor C:\n{random_tensor_C}\n')
print(f'Tensor D:\n{random_tensor_D}\n')

print(f'Does Tensor C is equal to Tensor D\n')
random_tensor_C==random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C is equal to Tensor D



tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [1]:
!nvidia-smi

Fri Dec  5 18:49:58 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   50C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [4]:
torch.cuda.device_count()

1

In [7]:
import torch
torch.backends.mps.is_available()

False

In [8]:
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [10]:
tensor_to_gpu = tensor.to(device)
tensor_to_gpu

tensor([1, 2, 3], device='cuda:0')

In [12]:
tensor_to_gpu.cpu().numpy()

array([1, 2, 3])